// <auto-generated />
using System;
using BudgetKeeper.Database.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetKeeper.Database.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20240529141621_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("BudgetKeeper.Database.Entity.CategoryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a76be85-d3ab-4901-bb73-0959b5f70f9d"),
                            Name = "Activities"
                        },
                        new
                        {
                            Id = new Guid("1c8a1709-26a1-49fb-aee0-77bec0413c50"),
                            Name = "Credit"
                        },
                        new
                        {
                            Id = new Guid("30e1211d-640d-40d0-84ab-b33736b2b998"),
                            Name = "Fine"
                        },
                        new
                        {
                            Id = new Guid("9d6a303a-5dd8-4f0c-af55-9fd13aed0dab"),
                            Name = "Gifts"
                        },
                        new
                        {
                            Id = new Guid("d12b01b0-21a8-4e27-8e4b-dd49a8e7c238"),
                            Name = "Health"
                        },
                        new
                        {
                            Id = new Guid("96abf42c-d4ce-4559-8769-e4aeb3924669"),
                            Name = "Preservation"
                        },
                        new
                        {
                            Id = new Guid("157e8737-e7b3-42a1-bb2c-3332f0767f52"),
                            Name = "Products"
                        },
                        new
                        {
                            Id = new Guid("9a60b64d-25eb-42df-ab0d-be39b82c9120"),
                            Name = "Salary"
                        },
                        new
                        {
                            Id = new Guid("eb79826e-f7f6-44b3-877b-668506eb10ed"),
                            Name = "Software"
                        },
                        new
                        {
                            Id = new Guid("9d516213-36d0-49ac-9e44-dda8001e2bd1"),
                            Name = "Taxes"
                        },
                        new
                        {
                            Id = new Guid("035698cd-aade-49a9-9193-6076c659b701"),
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("BudgetKeeper.Database.Entity.TransactionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetKeeper.Database.Entity.TransactionRecord", b =>
                {
                    b.HasOne("BudgetKeeper.Database.Entity.CategoryRecord", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
