// <auto-generated />
using System;
using BudgetKeeper.Database.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetKeeper.Database.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    partial class BudgetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("BudgetKeeper.Database.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee618fab-3ca9-4821-a714-1bee3a895a20"),
                            Name = "Activities"
                        },
                        new
                        {
                            Id = new Guid("52756aa3-c18a-4b22-920b-b9876812bc33"),
                            Name = "Credit"
                        },
                        new
                        {
                            Id = new Guid("7d062311-f7be-4fa9-b0cd-adebe8b6ddb9"),
                            Name = "Fine"
                        },
                        new
                        {
                            Id = new Guid("541ce086-51aa-4058-9207-9c10be773757"),
                            Name = "Gifts"
                        },
                        new
                        {
                            Id = new Guid("dc231561-697a-45ad-8348-9ae673a28ce2"),
                            Name = "Health"
                        },
                        new
                        {
                            Id = new Guid("8f812365-b6d9-425c-b690-6e4f4032de85"),
                            Name = "Preservation"
                        },
                        new
                        {
                            Id = new Guid("9cd17f10-7bf2-4a7a-98de-5615c6d74dcf"),
                            Name = "Products"
                        },
                        new
                        {
                            Id = new Guid("ccff22a7-cf17-4ca2-94b0-4f432c7833f8"),
                            Name = "Salary"
                        },
                        new
                        {
                            Id = new Guid("992f3450-832c-40ed-89ba-4389b7db8868"),
                            Name = "Software"
                        },
                        new
                        {
                            Id = new Guid("6eececdd-b7f8-41a5-9968-714d67b78a80"),
                            Name = "Taxes"
                        },
                        new
                        {
                            Id = new Guid("1bc72cc8-384b-4b2a-a3f5-16d1e6b23543"),
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("BudgetKeeper.Database.Entity.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetKeeper.Database.Entity.Transaction", b =>
                {
                    b.HasOne("BudgetKeeper.Database.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
