// <auto-generated />
using System;
using BudgetKeeper.Database.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetKeeper.Database.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    partial class BudgetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetKeeper.Database.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e12882ec-9c4a-403a-9886-c1c639e0ef0e"),
                            Name = "Activities"
                        },
                        new
                        {
                            Id = new Guid("3fd3c143-9f68-4cf0-b96a-e81d9766caa5"),
                            Name = "Credit"
                        },
                        new
                        {
                            Id = new Guid("52b86fab-3c94-4c2b-b90d-b967f1bcabcb"),
                            Name = "Fine"
                        },
                        new
                        {
                            Id = new Guid("7fd2297f-6bfb-4946-a8e4-8bd05818d7f8"),
                            Name = "Gifts"
                        },
                        new
                        {
                            Id = new Guid("83506bb3-b914-4a76-9e1c-b5798e148d1f"),
                            Name = "Health"
                        },
                        new
                        {
                            Id = new Guid("61487c48-8d66-4913-a1ed-1b996dff5be8"),
                            Name = "Preservation"
                        },
                        new
                        {
                            Id = new Guid("c49be0ad-65e4-4d31-9e58-5e68b622a2e6"),
                            Name = "Products"
                        },
                        new
                        {
                            Id = new Guid("9248ed7e-c127-4903-b32d-f0d3ff83ec31"),
                            Name = "Salary"
                        },
                        new
                        {
                            Id = new Guid("b96de06f-7af6-4cb4-9c6e-eed6253d612c"),
                            Name = "Software"
                        },
                        new
                        {
                            Id = new Guid("cf7281a2-7912-4e25-9f87-7657b1e333e6"),
                            Name = "Taxes"
                        },
                        new
                        {
                            Id = new Guid("7e10ea46-29dc-4e05-8626-5a94291f2ea1"),
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("BudgetKeeper.Database.Entity.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetKeeper.Database.Entity.Transaction", b =>
                {
                    b.HasOne("BudgetKeeper.Database.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
